apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: med-gauranshi-com-tls
spec:
  secretName: med-gauranshi-com
  issuerRef: 
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  dnsNames:
    - medgauranshi.com
    - www.medgauranshi.com
