apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: med-gauranshi-com-tls
spec:
  secretName: med-gauranshi-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: medgauranshi.com
  dnsNames:
    - medgauranshi.com
    - www.medgauranshi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - medgauranshi.com
          - www.medgauranshi.com
